services:
  dask-scheduler:
    build:
      context: .
      dockerfile: docker/jupyter/Dockerfile
    container_name: infraestructura-dask-scheduler
    command: dask scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    volumes:
      - ./data:/home/jovyan/data
      - ./sample_data_demo:/home/jovyan/sample_data_demo
      - ./output:/home/jovyan/output
      - ./dask/jobs:/home/jovyan/dask_jobs

  dask-worker:
    build:
      context: .
      dockerfile: docker/jupyter/Dockerfile
    container_name: infraestructura-dask-worker
    command: dask worker tcp://dask-scheduler:8786
    depends_on:
      - dask-scheduler
    environment:
      - DASK_DISTRIBUTED__WORKER__MEMORY__TARGET=0.8
    volumes:
      - ./data:/home/jovyan/data
      - ./sample_data_demo:/home/jovyan/sample_data_demo
      - ./output:/home/jovyan/output
      - ./dask/jobs:/home/jovyan/dask_jobs

  jupyter:
    build:
      context: .
      dockerfile: docker/jupyter/Dockerfile
    container_name: infraestructura-jupyter
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "dask"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./sample_data_demo:/home/jovyan/sample_data_demo
      - ./output:/home/jovyan/output
      - ./dask/jobs:/home/jovyan/dask_jobs
    depends_on:
      - dask-scheduler
      - dask-worker